### ISSUE TITLE
Instruction for GCP account and project setting

### ISSUE THREAD

**Issue by kazunori279** [BrainPad/FindYourCandy#17]
I think we need to have the "GCP for API service" instruction before the Linux setup, because Linux setup requires GCP account and project setting during the SDK installation.

Also, in the GCP instruction, it's better to have:

- Link to the instruction for GCP sign up and creating a new project for the demo
- List of GCP Services we will use for the robot and estimated cost when you run the robot for x hours

**Comment by max-hana** [comment]
Hmm...
GCP is now required prior to the execution of camera_tune.py .
... but that depends on webapp configuration.

**Comment by kazunori279** [comment]
Please refer to my pull request on README.md where I added a section for GCP setting. Feel free to move the section to any appropriate place in README or linux_box.md.

**Comment by max-hana** [comment]
Now updated.
