### ISSUE TITLE
How long does it take to update Dobot firmware?

### ISSUE THREAD

**Issue by kazunori279** [BrainPad/FindYourCandy#24]
I know this isn't a question for this project, but I'm having a trouble on updating the firmware of Dobot Magician.

- The robot arm works fine with my DobotStudio on Windows 10 Home.
- When I selected "DobotStudio Firmware..." menu, it shows "Dobot FM" tool
- I've chosen COM3, clicked "check" and confirmed the serial is working.
- But when I clicked "YES" button, it doesn't do anything. The progress bar stops at 0%. I left it for a while but nothing happens.

Did you see this?

**Comment by max-hana** [comment]
The robot company is using cheaper arduino and that may sometime cause troubles.
Get the latest driver for its chinese serial chip, to avoid the brood parasitism of using other company's driver which happens by default. (The honest company was probably angry about it, and made some tricks to the latest driver.)

I found very good page: 
http://0xcf.com/2015/03/13/chinese-arduinos-with-ch340-ch341-serial-usb-chip-on-os-x-yosemite/

I hope this helps.
(BTW, this did not happens with linux.)

It was quite well known to people playing with cheap aruduino(not genuine), but may be I should put some notice somewhere.

**Comment by kazunori279** [comment]
Thanks SO much!! After updating the driver, I was able to update the firmware.

Yeah, it's great to have notes for avoiding those pitfalls. Because the most important objective of this project is sharing Brain Pad's great solution with the ordinary developers like me, not the top data scientists or web engineer. The readiness of the document defines the value of this project.
