### ISSUE TITLE
Troubleshooting for "dobot offline" at Step 4.

### ISSUE THREAD

**Issue by kazunori279** [BrainPad/FindYourCandy#26]
At Step 4, I got "dobot offline" when I ran `robot_tune.py`. Can you add troubleshooting tips here? (such as checking the name of serial device, updating dobot firmware etc)

**Comment by kazunori279** [comment]
Actually I'm getting the error now and got stuck. What do I do?

**Comment by max-hana** [comment]
you need to chmod 777 /dev/ttyUSB0 after you plugged in USB to the linux box.

**Comment by kazunori279** [comment]
It worked!!! Thanks. Can you add an instruction to add it to .bashrc, as well as the $GOOGLE.. variable?

**Comment by kazunori279** [comment]
Another comment. When I do the calibration, I overlooked that there's the cross line for each marker, and that is the marker. I was moving the arm to the position of the letter A, D and E. Please modify the instruction to make it clearer.

**Comment by max-hana** [comment]
It's rather diffent topic.
- Marker target is now in thick color I'll update it soon.
- .bashrc is not good idea, we use ini files to set such variables.
