### ISSUE TITLE
word2vec model breaks git lfs

### ISSUE THREAD

**Issue by kazunori279** [BrainPad/FindYourCandy#28]
On installing the webapp, I got the [smudge filter lfs failed](https://github.com/git-lfs/git-lfs/issues/911) error on checking out the big model file. Can you change the README doc to download the file from original Google Drive? It's easier.

**Comment by max-hana** [comment]
It is documented here and our link only leads to the drive link, not the git you are refering to.
https://github.com/BrainPad/FindYourCandy/blob/master/webapp/README.md

**Comment by kazunori279** [comment]
Please see #29.
