### ISSUE TITLE
Provide .ini files and add instructions for them for initialization commands

### ISSUE THREAD

**Issue by kazunori279** [BrainPad/FindYourCandy#30]
When you reboot the PC, you need to execute some of the commands on the various parts of the documents by manual, such as $GOOGLE... env variable, /etc/tty.. permissions etc etc.

Every those commands should be automatically executed after rebooting, by using .ini file or else. This is a blocker for production release.

**Comment by max-hana** [comment]
- About permissions of /dev/ttyUSB0 and /dev/video0:
If you want permanent permission to the user, edit /etc/group to make some group to include.
Below is an example for user `brainpad` to grant the permisson. There is only two lines you need to edit.
  ```
  ...
  dialout:x:20:brainpad
  ...
  video:x:44:brainpad
  ...
  ```
I'll add this to linux_box.md.

- I merged your pull-request of .bashrc for $GOOGLE....

**Comment by kazunori279** [comment]
Please imagine a situation where no Linux technician available (maybe he's too busy/lunch/bathroom/sick leave etc) but the demo had some error. This happens so many times in any events/demo booths.

Only thing demo operator can do is rebooting the system. Are you sure that the current instruction assures the robustness where the system can initializes and start all required services properly without the technicians after rebooting?

**Comment by max-hana** [comment]
This is a cheap robot system. 
If things go wrong you cannot just reboot the system. In most case, robot and camera should be turned off-on, initialized or calibrated.

When we were developing this system, rebooting became only necessary for re-calibration of robot or camera.  (people accidentally interfered with robot arm or camera. ) To avoid it happen aluminium frames and a more expensive robot are required. As I recall this was suggestion at beginning of this project.

**Comment by kazunori279** [comment]
I'm just talking about simple thing: please separate instructions into two parts: 1) things you need to execute just once in the installation, and 2) things you need to execute every time you boot the system. The current instruction has both of them mixed and I can't tell which part is which one.

And then, it'd be much better if you can put the 2) part in .bashrc or any place that will be automatically executed after turning the power on. So you don't have to write detailed instruction for 2).
