### ISSUE TITLE
Add a link for downloading Inception v3 model on README of webapp

### ISSUE THREAD

**Issue by kazunori279** [BrainPad/FindYourCandy#31]
At the inception-V3 section of webapp README, 

- There's no link added for downloading Inception v3 model. Please add specific link to download
- It says "for Japanese from". I don't understand the meaning of this.

**Comment by kazunori279** [comment]
- `classify_image_graph_def.pb` file is not a compressed file. I got an error "not in gzip format" when I executed the `tar xvzf` command on it.

**Comment by rindai87** [comment]
I [fixed instruction](https://github.com/BrainPad/FindYourCandy/commit/f941eadc0383147d9017f1c72d3d3a1fea1e1303) .

- "for Japanese from" might be typo. so I deleted
- I added download link and modified sample command.

Can you retry this section?

**Comment by kazunori279** [comment]
Thanks for the quick reply! I was able to set up the files.
