### ISSUE TITLE
Add README.md under /setup

### ISSUE THREAD

**Issue by kazunori279** [BrainPad/FindYourCandy#6]
We will have many people finding this repo and reading the docs to reproduce the demo by themselves. Please prepare README.md for /setup folder that explains a procedure and links to each document to build the demo from scratch, such as:

1. Prepare hardware components
2. Setup hardware components
...

**Comment by max-hana** [comment]
That's what 'installation_instruction.md' was for, I guess.
so, we will rename it to README.md .

Besides that we are planning to rename other files in the same directory as well. 
Is it OK to you ? (this may broke some links from outside github if exist.)

**Comment by rindai87** [comment]
+1 to @max-hana.

I would like to proceed with that policy.

**Comment by kazunori279** [comment]
OK, please rename it to README.md and make sure all the instructions under /setup a linked from it. Also, we need to add a link to README.md from the top README.md.

**Comment by rindai87** [comment]
Thanks. We are considering a document construction. We'll rename and re-link in a few days.

**Comment by max-hana** [comment]
It's done.

**Comment by max-hana** [comment]
anyway, I guess it is quite obvious that I changed and added links.
if you have any suggestions, pls raise in a new issue.
